config/routes.rb
Rails.application.routes.draw do
  root 'top#main'
  resources :products
  get 'top/main'
  resources :cartitems,only: [:new, :create, :destroy]
  resources :carts,only: [:show, :destroy]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cartitems
    has_many :cartitem_products, through: :cartitems, source: :product
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :cartitems
    has_many :cartitem_carts, through: :cartitems, source: :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_cart
    private
       def current_cart
            if session[:cart_id]
                cart = Cart.find(session[:cart_id])
            else
                cart = Cart.create
                session[:cart_id] = cart.id
            end
            cart
        end
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
  def new
    @cart_id = current_cart.id
    @product_id = params[:product_id]
    @cartitem = Cartitem.new
  end

  def create
    @cart_id = params[:cartitem][:cart_id]
    @product_id = params[:cartitem][:product_id]
    @qty = params[:cartitem][:qty]
    c = Cartitem.new(cart_id: @cart_id, product_id: @product_id, qty: @qty)
    c.save
    redirect_to root_path
    #cartitem = Cartitem.new(cart_id: params[:cartitem][:cart_id],product_id: params[:cartitem][:product_id],qty: params[:cartitem][:qty], )
    #cartitem.save
    #redirect_to controller: :carts, action: :show, id: 1
  end

  def destroy
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cartitems = Cartitem.where(cart_id: current_cart.id)
  end
  
  def destroy
    cartitem = Cartitem.find(params[:id])
    cartitem.destroy
    redirect_to controller: :carts, action: :show, id: 1
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    current_cart
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    product = Product.new(name: params[:product][:name], price: params[:product][:price])
    product.save
    redirect_to products_path
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to products_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    redirect_to products_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cartitems/new.html.erb
<h1>
    カートアイテムページ
</h1>

<%= form_for @cartitem , url: {action: :create} do |f| %>
    商品名：<%= Product.find(@product_id).name %><br>
    価格：<%= Product.find(@product_id).price %><br>
    <%= f.label :qty, '数量' %>
    <%= f.text_field :qty %>
    <%= f.hidden_field :product_id, value: @product_id %>
    <%= f.hidden_field :cart_id, value: @cart_id %><br>
    <%= f.submit 'カートに登録する' %>
<% end %>

app/views/carts/show.html.erb
<h1>
    カートページ
</h1>

<% @cartitems.each do |e| %>
    <p>
        商品名：<%= Product.find(e.product_id).name %> &nbsp;
        価格：<%= Product.find(e.product_id).price %>円 &nbsp;
        数量：<%= e.qty %>
        <%= link_to "削除", "/carts/#{e.id}", data:{turbo_method: :delete} %>
    </p>
<% end %>
<%= link_to '商品一覧ページへ', products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopcart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>
    商品一覧ページ
</h1>

<% @products.each do |product| %>
<p>
    商品名：<%= product.name %> &nbsp;
    価格：<%= product.price %>円 &nbsp;
    <%= link_to "削除", "/products/#{product.id}", data:{turbo_method: :delete} %>
    <%= link_to "カート追加", new_cartitem_path(product_id: product.id),method: :post %>
</p>
<% end %>

<%= link_to "商品を追加する", new_product_path %><br>
<%= link_to "カートを見る", controller: :carts, action: :show, id: 1 %>

app/views/products/new.html.erb
<%= form_for @product , url: {action: :create} do |f| %>
    <%= f.label :name, '商品名称' %>
    <%= f.text_field :name %>
    <%= f.label :price, '商品価格' %>
    <%= f.text_field :price %>
    <%= f.submit '追加' %>
<% end %>

app/views/top/main.html.erb
<h1>Top#main</h1>
<p>Find me in app/views/top/main.html.erb</p>